services:
  - type: web
    name: pulsedesk-api
    env: docker
    plan: free
    rootDir: backend
    envVars:
      - key: APP_KEY
        value: "base64:0dGmcex4kbio1YnQzAgb2vY5qo+eOyn8grBwwiMTSWY="
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: pulsedesk-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: pulsedesk-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: pulsedesk-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: pulsedesk-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: pulsedesk-db
          property: password
      - key: FRONTEND_URL
        value: "https://your-frontend-url.vercel.app"

databases:
  - name: pulsedesk-db
    databaseName: pulsedesk
    user: pulsedesk_user
    plan: free
